#!/bin/sh
set -eu

# Docbase
if command -v install-docs >/dev/null 2>&1; then
 install-docs -r bzip2
fi

# Info
install-info --quiet --remove /usr/share/info/bzip2.info

# FHS
pkg=bzip2
if ( [ "$1" = "upgrade" ] || [ "$1" = "remove" ] ) && [ -L /usr/doc/$pkg ]; then
  rm -f /usr/doc/$pkg
fi
